name: Build and Publish Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Debian packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-make

    - name: Build Debian package
      run: |
        cd hello-world
        debuild -us -uc

    - name: Create APT repository structure
      run: |
        mkdir -p dists/stable/main/binary-amd64
        mkdir -p pool/main
        cp ../hello-world_1.0-1_amd64.deb pool/main/
        dpkg-scanpackages pool/main /dev/null | gzip -9c > dists/stable/main/binary-amd64/Packages.gz
        cat > dists/stable/Release <<EOF
        Origin: My APT Repository
        Label: My APT Repository
        Suite: stable
        Codename: stable
        Version: 1.0
        Architectures: amd64
        Components: main
        Description: My custom APT repository
        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dists
